version: 2

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/resources/code-template/csharp/deviceManageDeviceTwin"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/resources/code-template/csharp/sendD2C"
      schedule:
          interval: "daily"
      versioning-strategy: increase
