environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version
  - npm run version

build_script:
  - npm run vscode:prepublish

test_script:
  - npm run tslint